apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: docker.io/grafana/loki
  newTag: 2.4.0@sha256:413884a574a7ce52fd3adde46ba2ba1caaf441e17ae9e0de0c49c42f9dac61c4

resources:
- ../base
- loki-ingest-service.yaml
- loki-query-service.yaml
- loki-headless-service.yaml
- loki-statefulset.yaml

secretGenerator:
- name: loki
  files:
  - loki.yaml=standalone.config.yaml

configMapGenerator:
- name: fluentbit
  behavior: merge
  files:
  - outputs.conf=outputs-loki.conf
