apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: gossip
    port: 7946
    targetPort: gossip
  selector:
    app: loki
