apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../loki

images:
- name: docker.io/grafana/fluent-bit-plugin-loki
  newTag: 2.4.0-amd64@sha256:1b4f007631bc875c2bec3baeb2d0456b5091cdccc7b8a1843a387b82c8f7dce2

patchesStrategicMerge:
- fluentbit-loki-plugin.yaml

configMapGenerator:
- name: fluentbit
  behavior: merge
  files:
  - outputs.conf=outputs-loki-plugin.conf
  - labelmap.json
