apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Required for the ClusterRoleBinding in ../rbac
namespace: logs

resources:
- ../base

images:
- name: docker.io/grafana/fluent-bit-plugin-loki
  newTag: 2.5.0-amd64@sha256:9661313cc0bdb88c7aa89f23cf7de5832f01a44ae3868e7af20e1ba1f3b7e3d0

patchesStrategicMerge:
- fluentbit-loki-plugin.yaml

configMapGenerator:
- name: fluentbit
  behavior: merge
  files:
  - outputs.conf=outputs-loki-plugin.conf
  - labelmap.json
