apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../loki

images:
- name: docker.io/grafana/fluent-bit-plugin-loki
  newTag: latest@sha256:c5b84f0a41359c6dabdc27e30797157c82e5f440001723e5a6ae0fa255b12811

patchesStrategicMerge:
- fluentbit-loki-plugin.yaml

configMapGenerator:
- name: fluentbit
  behavior: merge
  files:
  - outputs.conf=outputs-loki-plugin.conf
  - labelmap.json

# distributed memberlist

replicas:
- name: loki
  count: 3

secretGenerator:
- name: loki
  behavior: merge
  files:
  - loki.yaml=distributed.config.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: loki
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: -distributor.replication-factor=3
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: -memberlist.rejoin-interval=60s
